/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
Leetcode 389
*/

class Solution {
    public char findTheDifference(String s, String t) {
        char[] count = new char[26];
        for(int i = 0;i<t.length();++i){
            count[t.charAt(i) - 'a']++;
        }
        for(int i = 0;i<s.length();++i){
            count[s.charAt(i) - 'a']--;
        }
        for(int i =0;i<26;++i){
            if(count[i] != 0)return (char)(i + 'a');
        }
        return 'a';
    }
}
